select * from customer_purchases ;
#Q1) what is total revenue generated by male vs female customers in diffrent category
select gender , Category , sum(purchase_amount_usd) as revenue
from customer_purchases
group by Gender , Category ;
Alter table customer_purchases
Rename column `Purchase Amount (USD)` to purchase_amount_usd ;


#Q2) which customer used a discount but still spend than averge purchase amount 
Alter table customer_purchases
Rename column `Discount Applied` to  discount_applied ;

select `Customer ID` , purchase_amount_usd
from customer_purchases
where discount_applied = "Yes" and purchase_amount_usd >=(select avg(purchase_amount_usd) from customer_purchases);

#Q3) which are top 5 products with the highest product review rating
SELECT 
    `Item Purchased`,
    round(AVG(`Review Rating`),2) AS average_review_rating
FROM customer_purchases
GROUP BY `Item Purchased`
ORDER BY average_review_rating DESC
LIMIT 5;

#Q4) Comapre the Averge purchase amount between Express and Standard Shipping
select `Shipping Type` , round(avg(purchase_amount_usd),2) as Averge_purchase_amount
from customer_purchases
where `Shipping Type` in('Standard' , 'Express')
group by `Shipping Type` ;

#Q5) Do Susbscribed customers spend more ? comapre Averge spend and total revenue between susbscribers and non-subscribers
select count(`Customer ID`) as total_customers , `Subscription Status`,
round(avg(purchase_amount_usd),2) as averge_spend,
round(sum(purchase_amount_usd),2) as revenue
from customer_purchases
group by `Subscription Status`
order by averge_spend , revenue desc;

#Q5) Which 5 products have highest percent of percenatge when discount applied
select `Item Purchased`,
round(100 * sum(case when discount_applied = "Yes" then 1 else 0 end)/count(*) ,2) as discount_rate
from customer_purchases
group by `Item Purchased`
order by discount_rate desc
limit 5 ;

#Q6) Segement Customers into new , Returning , and loyal based on therir total number
#number of previous purchases and show count of each segment

with customer_type as (
select `Customer ID` , `Previous Purchases`,
case
when `Previous Purchases` = 1 then "New" 
when `Previous Purchases` between 2 and 10 then "Returning"
Else "Loyal"
End as customer_segment
from customer_purchases
)
select customer_segment , count(*) as Number_of_Customers 
from customer_type
group by customer_segment ;

#Q7) what are top 3 products purchased within each category
with item_counts as(
select Category , `Item Purchased`,
count(`Customer ID`) as total_orders ,
row_number() over (partition by Category order by count(`Customer ID`) desc) as Item_rank
from customer_purchases
group by Category , `Item Purchased`
)
select Item_rank , Category ,`Item Purchased`,total_orders
from item_counts
where Item_rank<=3;

#Q8) Are Customers who are repeat buyers ( more than 5 previous purchases) alsol like to subscribe
select `Subscription Status` , count(`Customer ID`) as repeat_buyers
from customer_purchases
where `Previous Purchases`>5
group by `Subscription Status` ;

#Q9) what is the revenue contribution of each age group 
select age_group ,
sum(purchase_amount_usd) as revenue
from customer_purchases
group by age_group
order by revenue desc;















